apiVersion: v1
kind: Service
metadata:
  name: frontvote-service
spec:
  type: NodePort
  selector:
    app: frontvote
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
